#!/bin/bash
if [ ! -z `ls ./build` ]
then
    zip -9 -r -j source.love ssg/* -x build \*.git\* \*.app\* \*.love\* "*.DS_Store"
    mv source.love run.app/Contents/Resources/main.love #default naming convention as the wrapper is not signed or customized in any way
    open run.app
else
    echo "The directory you are currently in does NOT contain the build file that you try to run."
    echo "Please change into the directory that contains the build file and retry your action."
fi
